baseURL = "https://perl.com/"
languageCode = "en-us"
title = "Perl programming news, code and culture"
paginate = 30
disablePathToLower = true
[taxonomies]
author = "authors"
tag = "tags"
category = "categories"
[permalinks]
legacy=":slug"
[params]
github="https://github.com/dnmfarrell/perldotcom"
